version: 2
registries:
  npm:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    token: ${{secrets.GH_DUMMY}}
    replaces-base: true
  python:
    type: "python-index"
    url: "https://pypi.python.org/simple/"
    username: ${{secrets.GH_DUMMY_USERNAME}}
    password: ${{secrets.GH_DUMMY_PASSWORD}}
    replaces-base: true
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "./cloudflare" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      semver-major-days: 30
      semver-minor-days: 12
    registries:
      - npm
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: 'wrangler'

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - python
    insecure-external-code-execution: allow
    cooldown:
      default-days: 10
      semver-major-days: 30
      semver-minor-days: 12