name: "Clean Actions"
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"

permissions:
  actions: write

jobs:
  clean_actions:
    uses: theantiscamgroup/workflows/.github/workflows/clean_actions.yml@main
