name: "Clean Actions"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"

permissions:
  actions: write

jobs:
  # Clean up github job
  run:
    name: Cleanup
    uses: theantiscamgroup/workflows/.github/workflows/clean_actions.yml@main
