name: Deploy API Project
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'cloudflare/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '.github/**'
      - '!.github/filters.yml'

  workflow_dispatch:
    inputs:
        restart_bot:
            description: 'Restart API'
            required: true
            type: boolean
            default: false

# Prevent multiple instances of this action from running at once
concurrency:
  group: "deploy"
  cancel-in-progress: false

permissions:
  deployments: write
  contents: read

jobs:
  # Need to convert this input so that it's uniform, because default wasn't working
  workflow_check:
    name: Handle Workflow Input
    runs-on: ubuntu-latest
    outputs:
      should_restart: ${{ steps.solver.outputs.restart }}
    steps:
      - name: Need Force Restart Check
        id: solver
        run: |
          if $HAS_INPUT; then
            echo "restart=${{ github.event.inputs.restart_bot }}" >> "$GITHUB_OUTPUT"
          else
            echo "restart=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          HAS_INPUT: ${{ github.event.inputs.restart_bot != '' }}
      - name: Check Output
        run: echo ${{ steps.solver.outputs.restart }}
  deploy:
    name: Deploy Bot
    needs: workflow_check
    uses: theantiscamgroup/workflows/.github/workflows/deploy_bot.yml@main
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      path: "~/project/AntiScamBotAPI"
      force_restart: ${{ needs.workflow_check.outputs.should_restart == 'true' }}
