name: Deploy API Project
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'cloudflare/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '.github/**'
      - '!.github/workflows/deployapi.yml'
      - '!.github/filters.yml'

  workflow_dispatch:
    inputs:
        restart_bot:
            description: 'Restart API'
            required: true
            type: boolean

# Prevent multiple instances of this action from running at once
concurrency:
  group: "deploy"
  cancel-in-progress: false

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    uses: theantiscamgroup/workflows/.github/workflows/deploy_bot.yml@main
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      path: "~/project/AntiScamBotAPI"
      force_restart: ${{ github.event.inputs.restart_bot || false }}
