name: Update OpenAPI Spec

on:
  push:
    branches: ["main"]
    paths:
      - "main.py"
      - "requirements.txt"
      - ".github/workflows/openapi.yml"
  workflow_dispatch: {}

concurrency:
  group: openapi
  cancel-in-progress: false

permissions:
  contents: read
  actions: write
  deployments: write

jobs:
  make_openapi:
    uses: theantiscamgroup/workflows/.github/workflows/openapi.yml@main
    with:
      is_download: true
      clean_deploys: true
      download_uri: "https://api.scamguard.app/openapi.json"
      ref: ${{ github.ref }}
    # This probably will not work properly because of the org differences, but w/e
    # We can probably get around this by just forking the repo
    secrets: inherit
